[2019-02-01T11:54:47.079] [ERROR] system - { SequelizeUniqueConstraintError: Validation error
    at Query.formatError (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\sequelize\lib\dialects\mysql\query.js:226:16)
    at Query.handler [as onResult] (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\sequelize\lib\dialects\mysql\query.js:68:23)
    at Query.Command.execute (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\commands\command.js:30:12)
    at Connection.handlePacket (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:502:28)
    at PacketParser.onPacket (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:81:16)
    at PacketParser.executeStart (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\packet_parser.js:77:14)
    at Socket.<anonymous> (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:89:29)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:595:20)
  name: 'SequelizeUniqueConstraintError',
  errors: 
   [ ValidationErrorItem {
       message: 'username must be unique',
       type: 'unique violation',
       path: 'username',
       value: '',
       origin: 'DB',
       instance: [Object],
       validatorKey: 'not_unique',
       validatorName: null,
       validatorArgs: [] } ],
  fields: { username: '' },
  parent: 
   { Error: Duplicate entry '' for key 'username'
    at Packet.asError (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\packets\packet.js:716:13)
    at Query.Command.execute (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\commands\command.js:28:22)
    at Connection.handlePacket (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:502:28)
    at PacketParser.onPacket (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:81:16)
    at PacketParser.executeStart (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\packet_parser.js:77:14)
    at Socket.<anonymous> (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:89:29)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:595:20)
     code: 'ER_DUP_ENTRY',
     errno: 1062,
     sqlState: '23000',
     sqlMessage: 'Duplicate entry \'\' for key \'username\'',
     sql: 'INSERT INTO `UP_USER` (`id`,`username`,`password`,`nickname`,`level`,`rank`,`code`,`disabled`,`destroy`,`ctime`) VALUES (DEFAULT,\'\',\'d41d8cd98f00b204e9800998ecf8427e\',\'\',1,0,\'d41d8cd98f00b204e9800998ecf8427e\',false,false,\'2019-02-01 03:54:46\');' },
  original: 
   { Error: Duplicate entry '' for key 'username'
    at Packet.asError (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\packets\packet.js:716:13)
    at Query.Command.execute (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\commands\command.js:28:22)
    at Connection.handlePacket (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:502:28)
    at PacketParser.onPacket (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:81:16)
    at PacketParser.executeStart (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\packet_parser.js:77:14)
    at Socket.<anonymous> (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:89:29)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:595:20)
     code: 'ER_DUP_ENTRY',
     errno: 1062,
     sqlState: '23000',
     sqlMessage: 'Duplicate entry \'\' for key \'username\'',
     sql: 'INSERT INTO `UP_USER` (`id`,`username`,`password`,`nickname`,`level`,`rank`,`code`,`disabled`,`destroy`,`ctime`) VALUES (DEFAULT,\'\',\'d41d8cd98f00b204e9800998ecf8427e\',\'\',1,0,\'d41d8cd98f00b204e9800998ecf8427e\',false,false,\'2019-02-01 03:54:46\');' },
  sql: 'INSERT INTO `UP_USER` (`id`,`username`,`password`,`nickname`,`level`,`rank`,`code`,`disabled`,`destroy`,`ctime`) VALUES (DEFAULT,\'\',\'d41d8cd98f00b204e9800998ecf8427e\',\'\',1,0,\'d41d8cd98f00b204e9800998ecf8427e\',false,false,\'2019-02-01 03:54:46\');' }
[2019-02-01T11:54:47.810] [ERROR] system - { SequelizeUniqueConstraintError: Validation error
    at Query.formatError (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\sequelize\lib\dialects\mysql\query.js:226:16)
    at Query.handler [as onResult] (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\sequelize\lib\dialects\mysql\query.js:68:23)
    at Query.Command.execute (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\commands\command.js:30:12)
    at Connection.handlePacket (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:502:28)
    at PacketParser.onPacket (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:81:16)
    at PacketParser.executeStart (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\packet_parser.js:77:14)
    at Socket.<anonymous> (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:89:29)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:595:20)
  name: 'SequelizeUniqueConstraintError',
  errors: 
   [ ValidationErrorItem {
       message: 'username must be unique',
       type: 'unique violation',
       path: 'username',
       value: '',
       origin: 'DB',
       instance: [Object],
       validatorKey: 'not_unique',
       validatorName: null,
       validatorArgs: [] } ],
  fields: { username: '' },
  parent: 
   { Error: Duplicate entry '' for key 'username'
    at Packet.asError (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\packets\packet.js:716:13)
    at Query.Command.execute (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\commands\command.js:28:22)
    at Connection.handlePacket (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:502:28)
    at PacketParser.onPacket (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:81:16)
    at PacketParser.executeStart (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\packet_parser.js:77:14)
    at Socket.<anonymous> (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:89:29)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:595:20)
     code: 'ER_DUP_ENTRY',
     errno: 1062,
     sqlState: '23000',
     sqlMessage: 'Duplicate entry \'\' for key \'username\'',
     sql: 'INSERT INTO `UP_USER` (`id`,`username`,`password`,`nickname`,`level`,`rank`,`code`,`disabled`,`destroy`,`ctime`) VALUES (DEFAULT,\'\',\'d41d8cd98f00b204e9800998ecf8427e\',\'\',1,0,\'d41d8cd98f00b204e9800998ecf8427e\',false,false,\'2019-02-01 03:54:47\');' },
  original: 
   { Error: Duplicate entry '' for key 'username'
    at Packet.asError (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\packets\packet.js:716:13)
    at Query.Command.execute (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\commands\command.js:28:22)
    at Connection.handlePacket (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:502:28)
    at PacketParser.onPacket (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:81:16)
    at PacketParser.executeStart (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\packet_parser.js:77:14)
    at Socket.<anonymous> (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:89:29)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:595:20)
     code: 'ER_DUP_ENTRY',
     errno: 1062,
     sqlState: '23000',
     sqlMessage: 'Duplicate entry \'\' for key \'username\'',
     sql: 'INSERT INTO `UP_USER` (`id`,`username`,`password`,`nickname`,`level`,`rank`,`code`,`disabled`,`destroy`,`ctime`) VALUES (DEFAULT,\'\',\'d41d8cd98f00b204e9800998ecf8427e\',\'\',1,0,\'d41d8cd98f00b204e9800998ecf8427e\',false,false,\'2019-02-01 03:54:47\');' },
  sql: 'INSERT INTO `UP_USER` (`id`,`username`,`password`,`nickname`,`level`,`rank`,`code`,`disabled`,`destroy`,`ctime`) VALUES (DEFAULT,\'\',\'d41d8cd98f00b204e9800998ecf8427e\',\'\',1,0,\'d41d8cd98f00b204e9800998ecf8427e\',false,false,\'2019-02-01 03:54:47\');' }
[2019-02-01T11:54:48.524] [ERROR] system - { SequelizeUniqueConstraintError: Validation error
    at Query.formatError (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\sequelize\lib\dialects\mysql\query.js:226:16)
    at Query.handler [as onResult] (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\sequelize\lib\dialects\mysql\query.js:68:23)
    at Query.Command.execute (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\commands\command.js:30:12)
    at Connection.handlePacket (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:502:28)
    at PacketParser.onPacket (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:81:16)
    at PacketParser.executeStart (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\packet_parser.js:77:14)
    at Socket.<anonymous> (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:89:29)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:595:20)
  name: 'SequelizeUniqueConstraintError',
  errors: 
   [ ValidationErrorItem {
       message: 'username must be unique',
       type: 'unique violation',
       path: 'username',
       value: '',
       origin: 'DB',
       instance: [Object],
       validatorKey: 'not_unique',
       validatorName: null,
       validatorArgs: [] } ],
  fields: { username: '' },
  parent: 
   { Error: Duplicate entry '' for key 'username'
    at Packet.asError (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\packets\packet.js:716:13)
    at Query.Command.execute (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\commands\command.js:28:22)
    at Connection.handlePacket (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:502:28)
    at PacketParser.onPacket (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:81:16)
    at PacketParser.executeStart (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\packet_parser.js:77:14)
    at Socket.<anonymous> (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:89:29)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:595:20)
     code: 'ER_DUP_ENTRY',
     errno: 1062,
     sqlState: '23000',
     sqlMessage: 'Duplicate entry \'\' for key \'username\'',
     sql: 'INSERT INTO `UP_USER` (`id`,`username`,`password`,`nickname`,`level`,`rank`,`code`,`disabled`,`destroy`,`ctime`) VALUES (DEFAULT,\'\',\'d41d8cd98f00b204e9800998ecf8427e\',\'\',1,0,\'d41d8cd98f00b204e9800998ecf8427e\',false,false,\'2019-02-01 03:54:48\');' },
  original: 
   { Error: Duplicate entry '' for key 'username'
    at Packet.asError (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\packets\packet.js:716:13)
    at Query.Command.execute (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\commands\command.js:28:22)
    at Connection.handlePacket (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:502:28)
    at PacketParser.onPacket (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:81:16)
    at PacketParser.executeStart (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\packet_parser.js:77:14)
    at Socket.<anonymous> (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:89:29)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:595:20)
     code: 'ER_DUP_ENTRY',
     errno: 1062,
     sqlState: '23000',
     sqlMessage: 'Duplicate entry \'\' for key \'username\'',
     sql: 'INSERT INTO `UP_USER` (`id`,`username`,`password`,`nickname`,`level`,`rank`,`code`,`disabled`,`destroy`,`ctime`) VALUES (DEFAULT,\'\',\'d41d8cd98f00b204e9800998ecf8427e\',\'\',1,0,\'d41d8cd98f00b204e9800998ecf8427e\',false,false,\'2019-02-01 03:54:48\');' },
  sql: 'INSERT INTO `UP_USER` (`id`,`username`,`password`,`nickname`,`level`,`rank`,`code`,`disabled`,`destroy`,`ctime`) VALUES (DEFAULT,\'\',\'d41d8cd98f00b204e9800998ecf8427e\',\'\',1,0,\'d41d8cd98f00b204e9800998ecf8427e\',false,false,\'2019-02-01 03:54:48\');' }
[2019-02-01T11:54:48.662] [ERROR] system - { SequelizeUniqueConstraintError: Validation error
    at Query.formatError (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\sequelize\lib\dialects\mysql\query.js:226:16)
    at Query.handler [as onResult] (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\sequelize\lib\dialects\mysql\query.js:68:23)
    at Query.Command.execute (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\commands\command.js:30:12)
    at Connection.handlePacket (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:502:28)
    at PacketParser.onPacket (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:81:16)
    at PacketParser.executeStart (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\packet_parser.js:77:14)
    at Socket.<anonymous> (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:89:29)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:595:20)
  name: 'SequelizeUniqueConstraintError',
  errors: 
   [ ValidationErrorItem {
       message: 'username must be unique',
       type: 'unique violation',
       path: 'username',
       value: '',
       origin: 'DB',
       instance: [Object],
       validatorKey: 'not_unique',
       validatorName: null,
       validatorArgs: [] } ],
  fields: { username: '' },
  parent: 
   { Error: Duplicate entry '' for key 'username'
    at Packet.asError (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\packets\packet.js:716:13)
    at Query.Command.execute (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\commands\command.js:28:22)
    at Connection.handlePacket (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:502:28)
    at PacketParser.onPacket (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:81:16)
    at PacketParser.executeStart (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\packet_parser.js:77:14)
    at Socket.<anonymous> (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:89:29)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:595:20)
     code: 'ER_DUP_ENTRY',
     errno: 1062,
     sqlState: '23000',
     sqlMessage: 'Duplicate entry \'\' for key \'username\'',
     sql: 'INSERT INTO `UP_USER` (`id`,`username`,`password`,`nickname`,`level`,`rank`,`code`,`disabled`,`destroy`,`ctime`) VALUES (DEFAULT,\'\',\'d41d8cd98f00b204e9800998ecf8427e\',\'\',1,0,\'d41d8cd98f00b204e9800998ecf8427e\',false,false,\'2019-02-01 03:54:48\');' },
  original: 
   { Error: Duplicate entry '' for key 'username'
    at Packet.asError (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\packets\packet.js:716:13)
    at Query.Command.execute (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\commands\command.js:28:22)
    at Connection.handlePacket (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:502:28)
    at PacketParser.onPacket (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:81:16)
    at PacketParser.executeStart (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\packet_parser.js:77:14)
    at Socket.<anonymous> (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:89:29)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:595:20)
     code: 'ER_DUP_ENTRY',
     errno: 1062,
     sqlState: '23000',
     sqlMessage: 'Duplicate entry \'\' for key \'username\'',
     sql: 'INSERT INTO `UP_USER` (`id`,`username`,`password`,`nickname`,`level`,`rank`,`code`,`disabled`,`destroy`,`ctime`) VALUES (DEFAULT,\'\',\'d41d8cd98f00b204e9800998ecf8427e\',\'\',1,0,\'d41d8cd98f00b204e9800998ecf8427e\',false,false,\'2019-02-01 03:54:48\');' },
  sql: 'INSERT INTO `UP_USER` (`id`,`username`,`password`,`nickname`,`level`,`rank`,`code`,`disabled`,`destroy`,`ctime`) VALUES (DEFAULT,\'\',\'d41d8cd98f00b204e9800998ecf8427e\',\'\',1,0,\'d41d8cd98f00b204e9800998ecf8427e\',false,false,\'2019-02-01 03:54:48\');' }
[2019-02-01T11:54:48.825] [ERROR] system - { SequelizeUniqueConstraintError: Validation error
    at Query.formatError (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\sequelize\lib\dialects\mysql\query.js:226:16)
    at Query.handler [as onResult] (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\sequelize\lib\dialects\mysql\query.js:68:23)
    at Query.Command.execute (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\commands\command.js:30:12)
    at Connection.handlePacket (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:502:28)
    at PacketParser.onPacket (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:81:16)
    at PacketParser.executeStart (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\packet_parser.js:77:14)
    at Socket.<anonymous> (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:89:29)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:595:20)
  name: 'SequelizeUniqueConstraintError',
  errors: 
   [ ValidationErrorItem {
       message: 'username must be unique',
       type: 'unique violation',
       path: 'username',
       value: '',
       origin: 'DB',
       instance: [Object],
       validatorKey: 'not_unique',
       validatorName: null,
       validatorArgs: [] } ],
  fields: { username: '' },
  parent: 
   { Error: Duplicate entry '' for key 'username'
    at Packet.asError (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\packets\packet.js:716:13)
    at Query.Command.execute (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\commands\command.js:28:22)
    at Connection.handlePacket (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:502:28)
    at PacketParser.onPacket (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:81:16)
    at PacketParser.executeStart (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\packet_parser.js:77:14)
    at Socket.<anonymous> (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:89:29)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:595:20)
     code: 'ER_DUP_ENTRY',
     errno: 1062,
     sqlState: '23000',
     sqlMessage: 'Duplicate entry \'\' for key \'username\'',
     sql: 'INSERT INTO `UP_USER` (`id`,`username`,`password`,`nickname`,`level`,`rank`,`code`,`disabled`,`destroy`,`ctime`) VALUES (DEFAULT,\'\',\'d41d8cd98f00b204e9800998ecf8427e\',\'\',1,0,\'d41d8cd98f00b204e9800998ecf8427e\',false,false,\'2019-02-01 03:54:48\');' },
  original: 
   { Error: Duplicate entry '' for key 'username'
    at Packet.asError (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\packets\packet.js:716:13)
    at Query.Command.execute (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\commands\command.js:28:22)
    at Connection.handlePacket (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:502:28)
    at PacketParser.onPacket (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:81:16)
    at PacketParser.executeStart (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\packet_parser.js:77:14)
    at Socket.<anonymous> (D:\WebStorm 2017.2.2\day-day-up\src\day-day-up-back-server\node_modules\mysql2\lib\connection.js:89:29)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:595:20)
     code: 'ER_DUP_ENTRY',
     errno: 1062,
     sqlState: '23000',
     sqlMessage: 'Duplicate entry \'\' for key \'username\'',
     sql: 'INSERT INTO `UP_USER` (`id`,`username`,`password`,`nickname`,`level`,`rank`,`code`,`disabled`,`destroy`,`ctime`) VALUES (DEFAULT,\'\',\'d41d8cd98f00b204e9800998ecf8427e\',\'\',1,0,\'d41d8cd98f00b204e9800998ecf8427e\',false,false,\'2019-02-01 03:54:48\');' },
  sql: 'INSERT INTO `UP_USER` (`id`,`username`,`password`,`nickname`,`level`,`rank`,`code`,`disabled`,`destroy`,`ctime`) VALUES (DEFAULT,\'\',\'d41d8cd98f00b204e9800998ecf8427e\',\'\',1,0,\'d41d8cd98f00b204e9800998ecf8427e\',false,false,\'2019-02-01 03:54:48\');' }
